### ISSUE TITLE
Not working as of 0.5.4

### ISSUE THREAD

**Issue by ghost** [dracula/mousepad#1]
Well, it appears running the most recent version of Mousepad, it doesn't like the xml file I copied. Following the instructions carefully on the website.

These are the only options I get, even after restarting Mousepad and the OS:
![Screenshot_2021-05-04_13-10-37](https://user-images.githubusercontent.com/19254816/117050594-2431f080-acdb-11eb-8817-e59afd48deab.png)

**Comment by ghost** [comment]
If there are any other logs/output that I can present here, I can post them here for viewing.

**Comment by sistematico** [comment]
Same issue here.

- Arch Linux(updated)
- Xfce 4.16
- Mousepad 0.5.5

**Comment by sistematico** [comment]
More info: https://forum.xfce.org/viewtopic.php?pid=63158

**Comment by sistematico** [comment]
Solved.

```
cd tmp && git clone https://github.com/dracula/mousepad.git
mkdir -p ~/.local/share/gtksourceview-4/styles/
cp mousepad/dracula.xml ~/.local/share/gtksourceview-4/styles/
```

[More info](https://forum.xfce.org/viewtopic.php?pid=63159#p63159).

**Comment by ghost** [comment]
Yep, that worked. I'd just update the main page.
