### ISSUE TITLE
Not resolving markdown

### ISSUE THREAD

**Issue by ghost** [dracula/mousepad#3]
So, given the screenshot below, mousepad is not recognizing Markdown scripts correctly.

If there's anyway to get the coloring right for markdown, that would be awesome!

![Screenshot_2021-11-13_11-23-45](https://user-images.githubusercontent.com/19254816/141653329-64e9a25d-ac9e-4cd5-b01a-3bdbeea410a4.png)

**Comment by alvinseptiano** [comment]
Hey i'm currently working on the xml right now. i also reading the syntax specification and try to update as soon as possible. sorry for the hassle.

**Comment by alvinseptiano** [comment]
hey @GregTheHun, you can replace your `dracula.xml` from main branch now it support markdown.
